GAME_TURNS = 100

ROBOT_ORE_PER_TURN = 10
ROBOT_MAX_ORE_CAPACITY = 50

# rewards
REWARD_SMALL = 0.05
REWARD_MEDIUM = 0.2
REWARD_LARGE = 1

PENALTY_SMALL = -0.05
PENALTY_MEDIUM = -0.2
PENALTY_LARGE = -1

REWARD_SUCCESS = 100

REWARD_PER_TURN = PENALTY_SMALL
REWARD_PER_SCORE = REWARD_LARGE

REWARD_INVALID_ACTION = PENALTY_MEDIUM

REWARD_ORE_ALREADY_FULL = PENALTY_MEDIUM
REWARD_ORE_COLLECTED = REWARD_LARGE
REWARD_PER_RESOURCE_TRANSFERRED = REWARD_SMALL
REWARD_RESOURCE_WASTED = PENALTY_LARGE
REWARD_PER_RESOURCE_WASTED = PENALTY_SMALL