GAME_TURNS = 100

ROBOT_ORE_PER_TURN = 10
ROBOT_MAX_ORE_CAPACITY = 50

# rewards
REWARD_SMALL = 1
REWARD_MEDIUM = 2
REWARD_LARGE = 10

PENALTY_SMALL = -1
PENALTY_MEDIUM = -2
PENALTY_LARGE = -10

REWARD_SUCCESS = 1000

REWARD_PER_TURN = PENALTY_SMALL
REWARD_PER_SCORE = REWARD_LARGE

REWARD_INVALID_ACTION = PENALTY_SMALL

REWARD_ORE_ALREADY_FULL = PENALTY_MEDIUM
REWARD_ORE_COLLECTED = REWARD_LARGE
REWARD_PER_RESOURCE_TRANSFERRED = REWARD_MEDIUM
REWARD_RESOURCE_WASTED = PENALTY_LARGE
REWARD_PER_RESOURCE_WASTED = PENALTY_LARGE

# REWARD_PER_TURN = PENALTY_SMALL
# REWARD_PER_SCORE = 100

# REWARD_INVALID_ACTION = 0

# REWARD_ORE_ALREADY_FULL = 0
# REWARD_ORE_COLLECTED = REWARD_LARGE
# REWARD_PER_RESOURCE_TRANSFERRED = REWARD_MEDIUM
# REWARD_RESOURCE_WASTED = 0
# REWARD_PER_RESOURCE_WASTED = 0